// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aprlambvggnsvgxzscqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwcmxhbWJ2Z2duc3ZneHpzY3FtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNDY0NTgsImV4cCI6MjA3MzcyMjQ1OH0.30YQju2-6EHMIoc24pLIzjKZD_ZX-5Wis-OvhqCLoeE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});